### ISSUE TITLE
Failed to download nitrosdk-python from pypi.org

### ISSUE THREAD

**Issue by bts-dido** [pypi/support#1866]
### My Platform

We were able to download `nitrosdk-python` from pypi.org, but today suddenly getting 404 instead. Last successful attempt was about 23 hours ago - at 2022/4/20 09:11 UTC from our Travis server. 

```
$ python3.9 -m pip install nitrosdk-python -v
Using pip 20.2.3 from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip (python 3.9)
Non-user install because site-packages writeable
Created temporary directory: /private/var/folders/_t/ycfnwfvs12d8j779nptjd13w0000gn/T/pip-ephem-wheel-cache-2a2qh_o5
Created temporary directory: /private/var/folders/_t/ycfnwfvs12d8j779nptjd13w0000gn/T/pip-req-tracker-brv31yrl
Initialized build tracking at /private/var/folders/_t/ycfnwfvs12d8j779nptjd13w0000gn/T/pip-req-tracker-brv31yrl
Created build tracker: /private/var/folders/_t/ycfnwfvs12d8j779nptjd13w0000gn/T/pip-req-tracker-brv31yrl
Entered build tracker: /private/var/folders/_t/ycfnwfvs12d8j779nptjd13w0000gn/T/pip-req-tracker-brv31yrl
Created temporary directory: /private/var/folders/_t/ycfnwfvs12d8j779nptjd13w0000gn/T/pip-install-0mdk7jqp
1 location(s) to search for versions of nitrosdk-python:
* https://pypi.org/simple/nitrosdk-python/
Fetching project page and analyzing links: https://pypi.org/simple/nitrosdk-python/
Getting page https://pypi.org/simple/nitrosdk-python/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/nitrosdk-python/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/nitrosdk-python/ HTTP/1.1" 404 13
Status code 404 not in (200, 203, 300, 301)
Could not fetch URL https://pypi.org/simple/nitrosdk-python/: 404 Client Error: Not Found for url: https://pypi.org/simple/nitrosdk-python/ - skipping
Given no hashes to check 0 links for project 'nitrosdk-python': discarding no candidates
ERROR: Could not find a version that satisfies the requirement nitrosdk-python (from versions: none)
ERROR: No matching distribution found for nitrosdk-python
Exception information:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 323, in run
    requirement_set = resolver.resolve(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 339, in _get_abstract_dist_for
    self._populate_link(req)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 305, in _populate_link
    req.link = self._find_requirement_link(req)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 270, in _find_requirement_link
    best_candidate = self.finder.find_requirement(req, upgrade)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/index/package_finder.py", line 926, in find_requirement
    raise DistributionNotFound(
pip._internal.exceptions.DistributionNotFound: No matching distribution found for nitrosdk-python
WARNING: You are using pip version 20.2.3; however, version 22.0.4 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -m pip install --upgrade pip' command.
Removed build tracker: '/private/var/folders/_t/ycfnwfvs12d8j779nptjd13w0000gn/T/pip-req-tracker-brv31yrl'
```

### Fastly Debug

``` (paste your output on the next line)

```

### DNS Resolution

```console (paste your output after the line with the dig command)
$ dig pypi.org A
; <<>> DiG 9.10.6 <<>> pypi.org A
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1376
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;pypi.org.			IN	A

;; ANSWER SECTION:
pypi.org.		6935	IN	A	151.101.64.223
pypi.org.		6935	IN	A	151.101.128.223
pypi.org.		6935	IN	A	151.101.192.223
pypi.org.		6935	IN	A	151.101.0.223

;; Query time: 81 msec
;; SERVER: 203.165.31.152#53(203.165.31.152)
;; WHEN: Thu Apr 21 17:35:18 JST 2022
;; MSG SIZE  rcvd: 122

```

```console (paste your output after the line with the dig command)
$ dig pypi.org AAAA

```

```console (paste your output after the line with the dig command)
$ dig files.pythonhosted.org A

```

```console (paste your output after the line with the dig command)
$ dig files.pythonhosted.org AAAA

```

### Traceroutes / IPv4

```console (paste your output after the line with the traceroute command)
$ traceroute pypi.org

```

```console (paste your output after the line with the traceroute command)
$ traceroute files.pythonhosted.org

```

### Traceroutes / IPv6 (If available)

```console (paste your output after the line with the traceroute command)
$ traceroute6 pypi.org

```

```console (paste your output after the line with the traceroute command)
$ traceroute6 files.pythonhosted.org

```

### HTTPS Requests / IPv4

```console (paste your output after the line with the curl command)
$ curl -vvv -I --ipv4 https://pypi.org/pypi/pip/json
*   Trying 151.101.0.223...
* TCP_NODELAY set
* Connected to pypi.org (151.101.0.223) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=pypi.org
*  start date: Oct 22 18:55:44 2021 GMT
*  expire date: Nov 23 18:55:43 2022 GMT
*  subjectAltName: host "pypi.org" matched cert's "pypi.org"
*  issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign Atlas R3 DV TLS CA H2 2021
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f9e2100aa00)
> HEAD /pypi/pip/json HTTP/2
> Host: pypi.org
> User-Agent: curl/7.64.1
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 200 
HTTP/2 200 
< access-control-allow-headers: Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since
access-control-allow-headers: Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since
< access-control-allow-methods: GET
access-control-allow-methods: GET
< access-control-allow-origin: *
access-control-allow-origin: *
< access-control-expose-headers: X-PyPI-Last-Serial
access-control-expose-headers: X-PyPI-Last-Serial
< access-control-max-age: 86400
access-control-max-age: 86400
< cache-control: max-age=900, public
cache-control: max-age=900, public
< content-security-policy: base-uri 'self'; block-all-mixed-content; connect-src 'self' https://api.github.com/repos/ fastly-insights.com *.fastly-insights.com *.ethicalads.io https://api.pwnedpasswords.com https://2p66nmmycsj3.statuspage.io; default-src 'none'; font-src 'self' fonts.gstatic.com; form-action 'self'; frame-ancestors 'none'; frame-src 'none'; img-src 'self' https://warehouse-camo.ingress.cmh1.psfhosted.org/ www.google-analytics.com *.fastly-insights.com *.ethicalads.io; script-src 'self' www.googletagmanager.com www.google-analytics.com *.fastly-insights.com *.ethicalads.io 'sha256-U3hKDidudIaxBDEzwGJApJgPEf2mWk6cfMWghrAa6i0='; style-src 'self' fonts.googleapis.com *.ethicalads.io 'sha256-2YHqZokjiizkHi1Zt+6ar0XJ0OeEy/egBnlm+MDMtrM=' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='; worker-src *.fastly-insights.com
content-security-policy: base-uri 'self'; block-all-mixed-content; connect-src 'self' https://api.github.com/repos/ fastly-insights.com *.fastly-insights.com *.ethicalads.io https://api.pwnedpasswords.com https://2p66nmmycsj3.statuspage.io; default-src 'none'; font-src 'self' fonts.gstatic.com; form-action 'self'; frame-ancestors 'none'; frame-src 'none'; img-src 'self' https://warehouse-camo.ingress.cmh1.psfhosted.org/ www.google-analytics.com *.fastly-insights.com *.ethicalads.io; script-src 'self' www.googletagmanager.com www.google-analytics.com *.fastly-insights.com *.ethicalads.io 'sha256-U3hKDidudIaxBDEzwGJApJgPEf2mWk6cfMWghrAa6i0='; style-src 'self' fonts.googleapis.com *.ethicalads.io 'sha256-2YHqZokjiizkHi1Zt+6ar0XJ0OeEy/egBnlm+MDMtrM=' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='; worker-src *.fastly-insights.com
< content-type: application/json
content-type: application/json
< etag: "vC4FmLHphvYOHctuYMQq4w"
etag: "vC4FmLHphvYOHctuYMQq4w"
< referrer-policy: origin-when-cross-origin
referrer-policy: origin-when-cross-origin
< server: nginx/1.13.9
server: nginx/1.13.9
< x-pypi-last-serial: 13099085
x-pypi-last-serial: 13099085
< accept-ranges: bytes
accept-ranges: bytes
< date: Thu, 21 Apr 2022 08:38:27 GMT
date: Thu, 21 Apr 2022 08:38:27 GMT
< x-served-by: cache-iad-kiad7000142-IAD, cache-tyo11983-TYO
x-served-by: cache-iad-kiad7000142-IAD, cache-tyo11983-TYO
< x-cache: HIT, HIT
x-cache: HIT, HIT
< x-cache-hits: 76, 1
x-cache-hits: 76, 1
< x-timer: S1650530307.160402,VS0,VE1
x-timer: S1650530307.160402,VS0,VE1
< vary: Accept-Encoding, Accept-Encoding
vary: Accept-Encoding, Accept-Encoding
< strict-transport-security: max-age=31536000; includeSubDomains; preload
strict-transport-security: max-age=31536000; includeSubDomains; preload
< x-frame-options: deny
x-frame-options: deny
< x-xss-protection: 1; mode=block
x-xss-protection: 1; mode=block
< x-content-type-options: nosniff
x-content-type-options: nosniff
< x-permitted-cross-domain-policies: none
x-permitted-cross-domain-policies: none
< content-length: 137459
content-length: 137459

< 
* Connection #0 to host pypi.org left intact
* Closing connection 0

```

```console (paste your output after the line with the curl command)
$ curl -vvv -I --ipv4 https://files.pythonhosted.org/packages/ae/e8/2340d46ecadb1692a1e455f13f75e596d4eab3d11a57446f08259dee8f02/pip-10.0.1.tar.gz

```

### HTTPS Requests / IPv6 (If available)

```console (paste your output after the line with the curl command)
$ curl -vvv -I --ipv6 https://pypi.org/pypi/pip/json

```

```console (paste your output after the line with the curl command)
$ curl -vvv -I --ipv6 https://files.pythonhosted.org/packages/ae/e8/2340d46ecadb1692a1e455f13f75e596d4eab3d11a57446f08259dee8f02/pip-10.0.1.tar.gz

```

### TLS Debug / IPv4

```console (paste your output after the line with the openssl command)
$ echo -n | openssl s_client -4 -connect pypi.org:443
CONNECTED(00000005)
depth=2 OU = GlobalSign Root CA - R3, O = GlobalSign, CN = GlobalSign
verify return:1
depth=1 C = BE, O = GlobalSign nv-sa, CN = GlobalSign Atlas R3 DV TLS CA H2 2021
verify return:1
depth=0 CN = www.python.org
verify return:1
---
Certificate chain
 0 s:/CN=www.python.org
   i:/C=BE/O=GlobalSign nv-sa/CN=GlobalSign Atlas R3 DV TLS CA H2 2021
 1 s:/C=BE/O=GlobalSign nv-sa/CN=GlobalSign Atlas R3 DV TLS CA H2 2021
   i:/OU=GlobalSign Root CA - R3/O=GlobalSign/CN=GlobalSign
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIGpzCCBY+gAwIBAgIQAbfGzQPo4HG+SMKxp5lAdTANBgkqhkiG9w0BAQsFADBY
MQswCQYDVQQGEwJCRTEZMBcGA1UEChMQR2xvYmFsU2lnbiBudi1zYTEuMCwGA1UE
AxMlR2xvYmFsU2lnbiBBdGxhcyBSMyBEViBUTFMgQ0EgSDIgMjAyMTAeFw0yMTEw
MjIxODQxMTFaFw0yMjExMjMxODQxMTBaMBkxFzAVBgNVBAMMDnd3dy5weXRob24u
b3JnMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA9LggNSqPtkBioKAb
eomQ0Kff15MT/IiUU38vnApHUDB30rY9axYZY+o1faWd8vY/n8TlrmNnUdVv6OvM
6JyYjvN6Ry/lB+DQH5khCaCxbtZAFbl6XnK2IKQU/RndbTWLaAacW/gc6HUfByMd
TuQwBnay4cxOgs3yqQN9bIh9yW0PU9lISiscGUglC+Fg1B72LxppOeWJWxISZujo
AG98pm1APo1H5j8bOQHKrd4/lmBR/9Q6Q53AGQUDU/624zuVjvAp/Z07DGPcCva/
AVIZz3eV8IKtBwjoPZiQqobl6RgjMTD8CckEwrNS4+wy0OwLvqUNni1VZ+Z6k/3b
ZtGzgQIDAQABo4IDqjCCA6YwXwYDVR0RBFgwVoIOd3d3LnB5dGhvbi5vcmeCDCou
cHl0aG9uLm9yZ4IPZG9jcy5weXRob24ub3JnghRkb3dubG9hZHMucHl0aG9uLm9y
Z4IPcHlwaS5weXRob24ub3JnMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggr
BgEFBQcDAQYIKwYBBQUHAwIwHQYDVR0OBBYEFJN26IaF38fykujiYsJI7xYkx/pk
MFcGA1UdIARQME4wCAYGZ4EMAQIBMEIGCisGAQQBoDIKAQMwNDAyBggrBgEFBQcC
ARYmaHR0cHM6Ly93d3cuZ2xvYmFsc2lnbi5jb20vcmVwb3NpdG9yeS8wDAYDVR0T
AQH/BAIwADCBngYIKwYBBQUHAQEEgZEwgY4wQAYIKwYBBQUHMAGGNGh0dHA6Ly9v
Y3NwLmdsb2JhbHNpZ24uY29tL2NhL2dzYXRsYXNyM2R2dGxzY2FoMjIwMjEwSgYI
KwYBBQUHMAKGPmh0dHA6Ly9zZWN1cmUuZ2xvYmFsc2lnbi5jb20vY2FjZXJ0L2dz
YXRsYXNyM2R2dGxzY2FoMjIwMjEuY3J0MB8GA1UdIwQYMBaAFCo0uar6vzyI8Ufy
0hJ4vsXlqrBpMEgGA1UdHwRBMD8wPaA7oDmGN2h0dHA6Ly9jcmwuZ2xvYmFsc2ln
bi5jb20vY2EvZ3NhdGxhc3IzZHZ0bHNjYWgyMjAyMS5jcmwwggGABgorBgEEAdZ5
AgQCBIIBcASCAWwBagB3AG9Tdqwx8DEZ2JkApFEV/3cVHBHZAsEAKQaNsgiaN9kT
AAABfKlOkrUAAAQDAEgwRgIhAII5UIOyXvdQcRiBa9YOSeyDx2/wWzHQK64LefqW
cyZZAiEAp1+Lt6zCaagIwu6D6l3x1UpqZwvL3rAQMA7cprVrNEYAdwBGpVXrdfqR
IDC1oolp9PN9ESxBdL79SbiFq/L8cP5tRwAAAXypTpKwAAAEAwBIMEYCIQDWjDM7
Kq9hGiqN441efh80hvSvI8n1qjGR0YVezctuKAIhAMlJ0CS4C4W1To6/npYfYI2I
6zxNh/o/FFHtFrREQdTlAHYAVYHUwhaQNgFK6gubVzxT8MDkOHhwJQgXL6OqHQcT
0wwAAAF8qU6TIAAABAMARzBFAiA6B/M3ULcym41okykkdko2KtSYwjAf1+gTXgjk
SvDN7gIhAK2ZBwRKYaTiuQTa0z7R8CtgUTVwRnCk1eiTaHB2RL6BMA0GCSqGSIb3
DQEBCwUAA4IBAQBjJ9hl4W0AWlVgdQJfZAfL2oubfMPPG+nAdb3usfGBZhULFJ2G
R6cl1Yu2XY0x3oI3tkdeIlpmdIjT6W0RkYFj2dPgzkUk63UssZwzh/ZFpBkWX8gm
NpQyfRhrKm3WkJg++5Kxjtgthcl1LdMtSnQF60ZmJIrniCmx0Q9tstFDEIToA5Iz
ENiDjIJVGdYrSB+/Mu+LUfk663F1daqg29WVXqHvSknjbSk0xzKaxKWBOMjT8KFE
4G3CHwX2t4bj7IWFRIm4gTa04Rln7IWHjDRYN+pTGjPykB2JkkWlNNGJzvw/u0P5
/Lv5DpfLTrOag2HBbNLiXMfGWaiMq43af4PE
-----END CERTIFICATE-----
subject=/CN=www.python.org
issuer=/C=BE/O=GlobalSign nv-sa/CN=GlobalSign Atlas R3 DV TLS CA H2 2021
---
No client certificate CA names sent
Server Temp Key: ECDH, X25519, 253 bits
---
SSL handshake has read 3556 bytes and written 289 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: B90119EC11A3736CC634328DE12386D11CC486335FAF0FCDB6BE5CDFF489D6BB
    Session-ID-ctx: 
    Master-Key: 26FA926DEAD3194C7DB6AF014D0924EC4CF64F7E92373C72736BB3815F3CBE768F01587847980C455F17CBAB6BAC83C9
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - d1 ce 6b 18 0a 4c c6 4a-e4 c1 73 8c db 50 29 d7   ..k..L.J..s..P).
    0010 - ad d7 50 08 86 a2 f9 f9-b1 80 f1 24 53 81 c4 6f   ..P........$S..o
    0020 - 7f a7 31 cf 45 4f b6 83-d6 0b 79 05 b8 d8 c1 b9   ..1.EO....y.....
    0030 - 06 e7 7f 7f c9 9e 06 47-2a 5d 4a 21 de 92 34 55   .......G*]J!..4U
    0040 - 6e 1c 28 10 cd 66 63 df-96 c1 d1 e2 74 6c db fe   n.(..fc.....tl..
    0050 - a0 40 9a a5 7b 2c 01 a8-c7 72 0c 15 3a 95 f2 41   .@..{,...r..:..A
    0060 - 71 35 48 2f 73 ca 06 3c-4e 5d d4 01 41 c3 b7 97   q5H/s..<N]..A...
    0070 - c7 dd bd 7c ee 5d 25 fd-6f 14 f9 b6 12 ba ae 06   ...|.]%.o.......
    0080 - 3d 1c 4f 6d ea 54 3a bb-59 bc 60 c2 48 86 1b 24   =.Om.T:.Y.`.H..$
    0090 - 47 41 ac 29 4a 34 2d 1a-80 e6 c9 8d 25 0b 5c 44   GA.)J4-.....%.\D

    Start Time: 1650530329
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---
DONE

```

```console (paste your output after the line with the openssl command)
$ echo -n | openssl s_client -4 -connect files.pythonhosted.org:443

```

### TLS Debug / IPv6 (If available)

```console (paste your output after the line with the openssl command)
$ echo -n | openssl s_client -6 -connect pypi.org:443

```

```console (paste your output after the line with the openssl command)
$ echo -n | openssl s_client -6 -connect files.pythonhosted.org:443

```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
There is no project at https://pypi.org/project/nitrosdk-python/, which is why you're getting a 404.

**Comment by miketheman** [comment]
Closing, as the related issue also notes the package is not available on PyPI.
